import React from "react";
import Head from "next/head";
import Photo from "./photo/[id]";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Photo id={`0043`} isHome={true} />
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: { isHome: true },
  };
}
