import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Image
          src="/api/image/0001/square/600,/0/default.jpg"
          alt="0001"
          width="300"
          height="300"
        />
        <Image
          src="/api/image/0002/square/600,/0/default.jpg"
          alt="0002"
          width="300"
          height="300"
        />
      </main>
      <footer></footer>
    </div>
  );
}
